print('Bem vindo ao site de notas')
aluno = str(input('Digite seu nome:'))
materia = str(input('Digite a materia:'))
nota1 = float(input('Digite sua nota do Primeiro bimestre:'))
nota2 = float(input('Digite sua nota do Segundo bimestre:'))
nota3 = float(input('Digite sua nota do Terceiro bimestre:'))
nota4 = float(input('Digite sua nota do Quarto bimestre:'))
pontos = int(nota1 +nota2 + nota3 + nota4)
media = int(pontos/4)
print('Você possui {} pontos'.format(pontos))
print('Com uma media final de {} pontos'.format(media))
print('{} você precisa de um total de 28 pontos para passar de ano, ou seja uma media minima de 7,0'.format(aluno))
print('Você {0}, obteve um total de {1} pontos com uma media {2} em {3}'.format(aluno, pontos, media, materia))  
